### PR TITLE
CHRVariableTimer implementation, CHRTimer Protocol, CHRRepeatingTimer Protocol

### PR DESCRIPTION
**Pull request by comyar**

### CODE REVIEW

**Comment by comyar** [comment]
@eddies5 Can I get your feedback on this? Also for CHRCountdownTimer, make it conform to the CHRTimer protocol.

@schun93 This is the most up-to-date version of the variable timer that I have, just fyi.

**Comment by eddies5** [comment]
For all of the class methods for dispatch timer and variable timer I prefer a space after the first bracket: [[CHRDispatchTimer alloc] initWithInterval:interval executionBlock:executionBlock];

**Comment by eddies5** [comment]
I don't like the name "running" being used when that variable is actually representing a state of the timer.

**Comment by comyar** [comment]
Well the timer's state would be that it's running, right? What other name could it have? 

I will never ever in a million years put a space after the first bracket!

**Comment by eddies5** [comment]
I believe the space helps with readability.
The _running ivar changes to the different states in CHRTimerState, maybe _running can be named state or status.

**Comment by comyar** [comment]
Well, it's a private variable; it's all opaque to a user. CHRTimerState is in a private header and it's really just to improve readability internally. But the main case against naming it state is that the timer has multiple states at once. Its state can be valid/invalid and running/stopped at the same time.

**Comment by eddies5** [comment]
Having one enum with all the states was a bit confusing. Consider breaking up the CHRTimerState enum into several enums or somehow indicate that _running should only take on the Stopped and Running values and _valid should only take on the Valid and Invalid values.

**Comment by schun93** [comment]
For the test "testStartPauseInsideStartNowInside", the order of execution for the executionBlock should be delay, 0, 1, delay, 2, delay 3.

**Comment by comyar** [comment]
So I fixed the invocation block issue and updated the tests. The expected `nextInvocations` to the `intervalProvider` are potentially a little confusing (hence the previous behavior); an easy way to think about it is that the timer doesn't need to ask the `intervalProvider` for an interval when the user wants to start the timer immediately. 

Think of the base case where the timer hasn't started yet. If the user starts the timer immediately, the timer doesn't need to know the interval from the current time to the next invocation, right? Because the user said they wanted it to fire NOW. So we see the `executionBlock` called with `invocation=0` and `intervalProvider` called with `nextInvocation=1`; `nextInvocation=0` is skipped since the timer already knows that `invocation=0` should fire now (i.e. `interval=0.0`).

Hope that makes sense, I'll clarify if it's not clear. Correct me on anything if my reasoning is wrong.

**Comment by schun93** [comment]
Looks good  :+1:. That's actually what I did for the Swift version. Just added an if statement.

**Pull request merged**
